version: 2.1

orbs:
  node: circleci/node@4.7
  aws-s3: circleci/aws-s3@3.0
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: Bundle
          command: npm run bundle
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          context: aws-creds
          from: dist
          to: 's3://blocked-game'

  invalidate:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - aws-cli/setup:
          context: aws-creds
      - run:
          name: Invalidate Cloudfront distribution
          command: |
            aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID --paths=/*

workflows:
  sample:
    jobs:
      - node/test
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
      - invalidate:
          requires:
            - deploy
